replicaCount: 2
image:
  repository: 664418953285.dkr.ecr.ap-south-1.amazonaws.com/sample-app
  tag: "1"
service:
  port: 80
resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits: { memory: 128Mi }
